name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: blacksmith-8vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: fmt
        run: test -z $(gofmt -l . | head -n 1) || ( gofmt -d . ; exit 1 )

      - name: vet
        run: go vet ./...

      - name: test
        run: go test ./...

      - uses: dominikh/staticcheck-action@v1
        with:
          version: '2025.1.1'
          install-go: false
